author: Aniket Modi
email: aniket.modi117@gmail.com
title: Not a blog
description: > # this means to ignore newlines until "baseurl:"
  Welcome!

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# social links
twitter_username: aniketm117 # DO NOT include the @ character, or else the build will fail!
github_username:  aniketm117 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
