title: Not a blog
author: Aniket Modi
email: aniket.modi117@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Not a blog

remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# social links
twitter_username: aniketm117 # DO NOT include the @ character, or else the build will fail!
github_username:  aniketm117 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
